# Generated by Django 6.1.1 on 2026-09-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('soil_type', models.CharField(blank=True, max_length=200)),
                ('climate', models.CharField(blank=True, max_length=200)),
                ('planting_method', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('symptoms', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='crops.crop')),
            ],
            options={
                'ordering': ['crop__name', 'name'],
                'unique_together': {('crop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FertilizerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_stage', models.CharField(max_length=100)),
                ('fertilizer_guidance', models.TextField()),
                ('irrigation_guidance', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text="Stage order within the crop's timeline")),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_schedules', to='crops.crop')),
            ],
            options={
                'ordering': ['crop__name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('duration_description', models.CharField(blank=True, max_length=200)),
                ('details', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_stages', to='crops.crop')),
            ],
            options={
                'ordering': ['crop__name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OrganicManureMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('materials', models.TextField()),
                ('steps', models.TextField()),
                ('crops', models.ManyToManyField(blank=True, related_name='organic_methods', to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_info', models.TextField()),
                ('preventive_measures', models.TextField(blank=True)),
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='crops.disease')),
            ],
        ),
    ]
