# Generated by Django 6.1 on 2026-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="intercropped_with",
            field=models.ManyToManyField(blank=True, to="crops.crop"),
        ),
    ]
