# Generated by Django 6.1 on 2026-09-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0002_crop_intercropped_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="climate_hi",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Climate (Hindi)"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="climate_kn",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Climate (Kannada)"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="name_hi",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Name (Hindi)"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="name_kn",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Name (Kannada)"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="planting_method_hi",
            field=models.TextField(blank=True, verbose_name="Planting method (Hindi)"),
        ),
        migrations.AddField(
            model_name="crop",
            name="planting_method_kn",
            field=models.TextField(
                blank=True, verbose_name="Planting method (Kannada)"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="soil_type_hi",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Soil type (Hindi)"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="soil_type_kn",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Soil type (Kannada)"
            ),
        ),
    ]
